import { StyleSheet } from 'react-native';

export const PesquisaStyles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
  },
  headerBar: {
    backgroundColor: '#F4F0FA',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#2c1a5a',
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2d114b',
    letterSpacing: -0.2,
  },
  titleIconWrap: {
    width: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  titleIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
  },
  card: {
    marginTop: 8,
    width: '100%',
    backgroundColor: '#F4F0FA',
    borderWidth: 2,
    borderColor: '#2C106D',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 12,
  },
  searchBox: {
    width: '100%',
    height: 40,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#00000031',
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  highlightIcon : {
    marginRight: 5,
  },
  searchInput: {
    flex: 1,
    height: '100%',
    fontSize: 14,
    color: '#1f2937',
  },
  searchIconWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  sectionTitle: {
    width: '100%',
    fontSize: 14,
    fontWeight: '700',
    color: '#2d114b',
    marginTop: 16,
    marginBottom: 8,
  },
  highlightList: {
    width: '100%',
    backgroundColor: '#e8e2f0',
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderWidth: 0,
  },
  highlightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
  },
  highlightDot: {
    color: '#f0c128',
    fontSize: 16,
    marginRight: 10,
  },
  highlightText: {
    fontSize: 13,
    color: '#1b1b1b',
    fontWeight: '600',
  },
  grid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  faceCard: {
    width: '48.8%',
    height: 160,
    backgroundColor: '#000000',
    borderWidth: 2,
    borderColor: '#2c1a5a',
    borderRadius: 10,
    marginBottom: 10,
    overflow: 'hidden',
    position: 'relative',
  },
  starTopLeft: {
    position: 'absolute',
    left: 8,
    top: 8,
    zIndex: 2,
  },
  starTopRight: {
    position: 'absolute',
    right: 8,
    top: 8,
    zIndex: 2,
  },
  star: {
    color: '#f0c128',
    fontSize: 16,
  },
  eyeLeft: {
    position: 'absolute',
    left: '15%',
    top: '28%',
    width: 64,
    height: 64,
    borderRadius: 40,
    borderWidth: 5,
    borderColor: '#4ff0c6',
    backgroundColor: '#090909',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4ff0c6',
    shadowOpacity: 0.7,
    shadowRadius: 10,
    elevation: 5,
  },
  eyeRight: {
    position: 'absolute',
    right: '15%',
    top: '28%',
    width: 64,
    height: 64,
    borderRadius: 40,
    borderWidth: 5,
    borderColor: '#4ff0c6',
    backgroundColor: '#090909',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4ff0c6',
    shadowOpacity: 0.7,
    shadowRadius: 10,
    elevation: 5,
  },
  eyeInner: {
    width: 38,
    height: 38,
    borderRadius: 22,
    backgroundColor: '#4ff0c6',
    shadowColor: '#4ff0c6',
    shadowOpacity: 0.9,
    shadowRadius: 12,
  },
  mouth: {
    position: 'absolute',
    left: '18%',
    right: '18%',
    bottom: 18,
    height: 28,
    borderBottomWidth: 8,
    borderBottomColor: '#4ff0c6',
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
  },
  faceImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
});
