import { StyleSheet } from "react-native";

export const Feedstyles = StyleSheet.create({
    container_gradient : {

    },


    Main_feed : {
        flex: 1,
        width: '100%',
        alignItems: 'center',
        paddingTop: 12,
    },
    Header : {
        backgroundColor: 'rgba(255,255,255,0.94)',
        borderRadius: 18,
        borderWidth: 2,
        borderColor: '#2C106D',
        paddingHorizontal: 14,
        paddingVertical: 10,
        flexDirection: 'row',
        width: '95%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 3,
    },
    HeaderText : {
        fontSize: 22,
        fontWeight: '700',
        color: '#2E1065',
        marginLeft: 6,
    },
    Logo : {
        width: 20,
        height: 20,
        marginTop: 2.5,
        marginLeft: 9,
    },
    SearchButton: {
        padding: 6,
        marginLeft: 'auto',
    },
    Search : {
        width: 20,
        height: 20,
    },
    feedScroll: {
        width: '100%',
        flex: 1,
    },
    feedContent: {
        alignItems: 'center',
        paddingVertical: 16,
        paddingBottom: 28,
    },
    PostCard: {
        width: '95%',
        backgroundColor: '#F7F7FA',
        borderRadius: 18,
        borderWidth: 2,
        borderColor: '#2C106D',
        paddingHorizontal: 14,
        paddingTop: 12,
        paddingBottom: 10,
        marginBottom: 18,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    PostHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    AvatarWrap: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: '#8b5cf6',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#ffffff',
        overflow: 'hidden',
    },
    AvatarImage: {
        width: '100%',
        height: '100%',
        borderRadius: 19,
    },
    UserTextWrap: {
        flex: 1,
        marginLeft: 10,
    },
    UserName: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1f1f1f',
    },
    MetaText: {
        fontSize: 11,
        color: '#6b7280',
        marginTop: 2,
    },
    MenuButton: {
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    MenuDots: {
        fontSize: 18,
        color: '#1f2937',
        letterSpacing: 1,
    },
    PostText: {
        fontSize: 14,
        lineHeight: 18,
        color: '#20232a',
        marginBottom: 10,
    },
    artwork: {
        width: '100%',
        height: 210,
        borderRadius: 14,
        backgroundColor: '#000000',
        overflow: 'hidden',
        marginBottom: 10,
        position: 'relative',
    },
    eye: {
        position: 'absolute',
        top: '18%',
        width: 110,
        height: 110,
        borderRadius: 60,
        borderWidth: 6,
        backgroundColor: '#0b0b0b',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#5ef9d6',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.7,
        shadowRadius: 10,
        elevation: 4,
    },
    eyeInner: {
        width: 70,
        height: 70,
        borderRadius: 40,
        shadowColor: '#5ef9d6',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 14,
    },
    eyeHighlight: {
        position: 'absolute',
        width: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: '#fff',
        top: 18,
        left: 24,
        opacity: 0.9,
    },
    mouthWrap: {
        position: 'absolute',
        left: '15%',
        right: '15%',
        bottom: 16,
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
    },
    mouth: {
        width: '72%',
        height: 30,
        borderBottomWidth: 8,
        borderLeftWidth: 0,
        borderRightWidth: 0,
        borderTopWidth: 0,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        borderColor: '#5ef9d6',
    },
    ActionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: 12,
        paddingTop: 2,
    },
    ActionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 10,
    },
    ActionIcon: {
        fontSize: 14,
        color: '#1f2937',
        marginRight: 6,
    },
    ActionText: {
        fontSize: 12,
        color: '#555',
    },
    ActionItemShare: {
        marginLeft: 'auto',
        paddingHorizontal: 4,
    },
    ActionIconShare: {
        fontSize: 11,
        color: '#40404088',
    },
    PostImage: {
        width: '100%',
        height: 210,
        borderRadius: 14,
        marginBottom: 10,
        backgroundColor: '#000',
    },
})


